version: '3.8'

services:
  wordpress:
    image: wordpress:6.4
    user: "33:33"
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
    volumes:
      - ./wp-data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --skip-name-resolve
    ports:
      - "3306:3306"  # ← 追加！
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - db_data:/var/lib/mysql

  flask:
    build: ./flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - wordpress
      - flask

volumes:
  db_data:
